config/routes.rb
Rails.application.routes.draw do
  get 'works/index'
  root 'works#index'
  delete 'works/delete/:id' => 'works#destroy', as: :delete_work

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :inventories
end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  belongs_to :category
  has_one :work, dependent: :destroy
  validates :serial, presence: true, uniqueness: true
  validates :wheelsize, numericality: { greater_than: 0 }
  after_destroy :register_item_deleted

  scope :with_size, ->(s) { where(wheelsize: s) }

  def register_item_deleted
  	r = Register.new(description: "La pieza con serial #{serial} ha sido borrada")
  	r.save
  end
end

app/models/register.rb
class Register < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :works, dependent: :destroy
	validates :name, presence: true
end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :user
  belongs_to :inventory

  scope :last_5, -> { order(id: :desc).limit(5) }
  scope :no_items, ->  { where(inventory_id: nil) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
  	@works = Work.all
  end

  def destroy
  	@work = Work.find(params[:id])
  	@work.destroy
  	redirect_to works_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prueba2Rcereceda</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/works/index.html.erb
<h1>Works</h1>

<ul>
	<% @works.each do |w| %>
	<li>
		<%= w.description %>, realizado por: <%= w.user.name %>, ítem: <%= w.inventory.description %> (Categoría: <%= w.inventory.category.name %>)
		<a href="<%= delete_work_path(w.id) %>" data-method="delete">Borrar</a>
	</li>
	<% end %>
</ul>